### ISSUE TITLE
How to configure externalTrafficPolicy

### ISSUE THREAD

**Issue by wangchao732** [emqx/emqx-operator#1094]
EMQX: 5.8.3
EMQX-EXPORTER: 2.0
K8S: 1.24.x

The service configuration has been automatically restored.

An error occurred while configuring in CRDS. EMQX-exporter Keep restarting.

2024-12-23T18:56:39.857969980+08:00 {“level”:“info”,“ts”:“2024-12-23T10:56:39Z”,“logger”:“controller-runtime.metrics”,“msg”:“Starting metrics server”}

2024-12-23T18:56:39.858085541+08:00 {“level”:“info”,“ts”:“2024-12-23T10:56:39Z”,“logger”:“controller-runtime.webhook”,“msg”:“Starting webhook server”}

2024-12-23T18:56:39.858097105+08:00 {“level”:“info”,“ts”:“2024-12-23T10:56:39Z”,“logger”:“controller-runtime.metrics”,“msg”:“Serving metrics server”,“bindAddress”:“:8080”,“secure”:false}

2024-12-23T18:56:39.858511721+08:00 I1223 10:56:39.858359 1 leaderelection.go:250] attempting to acquire leader lease emqx-operator-system/19fd6fcc.emqx.io…

2024-12-23T18:56:39.858930574+08:00 {“level”:“info”,“ts”:“2024-12-23T10:56:39Z”,“logger”:“controller-runtime.certwatcher”,“msg”:“Updated current TLS certificate”}

2024-12-23T18:56:39.859148169+08:00 {“level”:“info”,“ts”:“2024-12-23T10:56:39Z”,“logger”:“controller-runtime.webhook”,“msg”:“Serving webhook server”,“host”:“”,“port”:9443}

2024-12-23T18:56:39.859748543+08:00 {“level”:“info”,“ts”:“2024-12-23T10:56:39Z”,“logger”:“controller-runtime.certwatcher”,“msg”:“Starting certificate watcher”}

2024-12-23T18:57:11.927754881+08:00 I1223 10:57:11.926574 1 leaderelection.go:260] successfully acquired lease emqx-operator-system/19fd6fcc.emqx.io

2024-12-23T18:57:11.928070987+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting EventSource”,“controller”:“emqxbroker”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EmqxBroker”,“source”:“kind source: *v1beta4.EmqxBroker”}

2024-12-23T18:57:11.928086197+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting EventSource”,“controller”:“emqxplugin”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EmqxPlugin”,“source”:“kind source: *v1beta4.EmqxPlugin”}

2024-12-23T18:57:11.928092637+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting Controller”,“controller”:“emqxplugin”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EmqxPlugin”}

2024-12-23T18:57:11.928097577+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting Controller”,“controller”:“emqxbroker”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EmqxBroker”}

2024-12-23T18:57:11.928107704+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting EventSource”,“controller”:“emqx”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EMQX”,“source”:“kind source: *v2beta1.EMQX”}

2024-12-23T18:57:11.928113561+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting Controller”,“controller”:“emqx”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EMQX”}

2024-12-23T18:57:11.928118404+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting EventSource”,“controller”:“rebalance”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“Rebalance”,“source”:“kind source: *v2beta1.Rebalance”}

2024-12-23T18:57:11.928164404+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting Controller”,“controller”:“rebalance”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“Rebalance”}

2024-12-23T18:57:11.928172821+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting EventSource”,“controller”:“emqxenterprise”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EmqxEnterprise”,“source”:“kind source: *v1beta4.EmqxEnterprise”}

2024-12-23T18:57:11.928259402+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:11Z”,“msg”:“Starting Controller”,“controller”:“emqxenterprise”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EmqxEnterprise”}

2024-12-23T18:57:12.031694121+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:12Z”,“msg”:“Starting workers”,“controller”:“emqxbroker”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EmqxBroker”,“worker count”:1}

2024-12-23T18:57:12.035944053+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:12Z”,“msg”:“Starting workers”,“controller”:“emqxenterprise”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EmqxEnterprise”,“worker count”:1}

2024-12-23T18:57:12.036217738+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:12Z”,“msg”:“Starting workers”,“controller”:“rebalance”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“Rebalance”,“worker count”:1}

2024-12-23T18:57:12.036237438+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:12Z”,“msg”:“Starting workers”,“controller”:“emqxplugin”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EmqxPlugin”,“worker count”:1}

2024-12-23T18:57:12.036243575+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:12Z”,“msg”:“Starting workers”,“controller”:“emqx”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EMQX”,“worker count”:1}

2024-12-23T18:57:12.829092732+08:00 {“level”:“info”,“ts”:“2024-12-23T10:57:12Z”,“msg”:“Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference”,“controller”:“emqx”,“controllerGroup”:“[apps.emqx.io](http://apps.emqx.io/)”,“controllerKind”:“EMQX”,“EMQX”:{“name”:“emqx”,“namespace”:“default”},“namespace”:“default”,“name”:“emqx”,“reconcileID”:“4eff0edd-ad89-4281-b7ee-c4cf37aa21bd”}

2024-12-23T18:57:12.831276175+08:00 panic: runtime error: invalid memory address or nil pointer dereference [recovered]

2024-12-23T18:57:12.831293965+08:00 panic: runtime error: invalid memory address or nil pointer dereference

2024-12-23T18:57:12.831299015+08:00 [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x177e3c0]

2024-12-23T18:57:12.831303368+08:00

2024-12-23T18:57:12.831309132+08:00 goroutine 244 [running]:

2024-12-23T18:57:12.831313905+08:00 [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1())

2024-12-23T18:57:12.831333235+08:00 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:116 +0x1e5

2024-12-23T18:57:12.831338942+08:00 panic({0x195d920?, 0x2c00a90?})

2024-12-23T18:57:12.831344325+08:00 /usr/local/go/src/runtime/panic.go:770 +0x132

2024-12-23T18:57:12.831414939+08:00 [github.com/emqx/emqx-operator/controllers/apps/v2beta1.(*updateStatus).reconcile](http://github.com/emqx/emqx-operator/controllers/apps/v2beta1.(*updateStatus).reconcile)(0xc00008e070, {0x1e76ac8, 0xc00089a5d0}, {{0xc0000c45a0?, 0xc000131208?}, 0xc00089a5d0?}, 0xc000131208, {0x1e78aa0, 0xc000661880})

2024-12-23T18:57:12.831444119+08:00 /workspace/controllers/apps/v2beta1/update_emqx_status.go:122 +0x860

2024-12-23T18:57:12.831501056+08:00 [github.com/emqx/emqx-operator/controllers/apps/v2beta1.(*EMQXReconciler).Reconcile](http://github.com/emqx/emqx-operator/controllers/apps/v2beta1.(*EMQXReconciler).Reconcile)(0xc0004a0ab0, {0x1e76ac8, 0xc00089a5d0}, {{{0xc000889c90?, 0x5?}, {0xc000889c8c?, 0xc0003afd10?}}})

2024-12-23T18:57:12.831521640+08:00 /workspace/controllers/apps/v2beta1/emqx_controller.go:137 +0x7c3

2024-12-23T18:57:12.831586754+08:00 [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile)(0x1e7afb8?, {0x1e76ac8?, 0xc00089a5d0?}, {{{0xc000889c90?, 0xb?}, {0xc000889c8c?, 0x0?}}})

2024-12-23T18:57:12.831630847+08:00 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119 +0xb7

2024-12-23T18:57:12.831650178+08:00 [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler)(0xc000014f00, {0x1e76b00, 0xc00048f180}, {0x1a0de80, 0xc0001bc040})

2024-12-23T18:57:12.831654964+08:00 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316 +0x3bc

2024-12-23T18:57:12.831691888+08:00 [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem)(0xc000014f00, {0x1e76b00, 0xc00048f180})

2024-12-23T18:57:12.831697361+08:00 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266 +0x1be

2024-12-23T18:57:12.831709155+08:00 [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2())

2024-12-23T18:57:12.831720861+08:00 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227 +0x79

2024-12-23T18:57:12.831731565+08:00 created by [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2) in goroutine 136

2024-12-23T18:57:12.831760818+08:00 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:223 +0x50c

apiVersion: [apps.emqx.io/v2alpha1](http://apps.emqx.io/v2alpha1)
kind: EMQX
metadata:
annotations:
[apps.emqx.io/last-emqx-configuration:](http://apps.emqx.io/last-emqx-configuration:) ‘’
[kubectl.kubernetes.io/last-applied-configuration:](http://kubectl.kubernetes.io/last-applied-configuration:) >
{“apiVersion”:“[apps.emqx.io/v2beta1",“kind”:“EMQX”,“metadata”:{“annotations”:{},“name”:“emqx”,“namespace”:“default”},“spec”:{“coreTemplate”:{“spec”:{“volumeClaimTemplates”:{“accessModes”:[“ReadWriteOnce”],“resources”:{“requests”:{“storage”:“5Gi”}},“storageClassName”:“nfs-client”}}},“dashboardServiceTemplate”:{“spec”:{“type”:“LoadBalancer”}},“image”:“registry.cn-hongkong.aliyuncs.com/bcldops/emqx:5.8.3”,“listenersServiceTemplate”:{“spec”:{“type”:"LoadBalancer](http://apps.emqx.io/v2beta1%22,%22kind%22:%22EMQX%22,%22metadata%22:%7B%22annotations%22:%7B%7D,%22name%22:%22emqx%22,%22namespace%22:%22default%22%7D,%22spec%22:%7B%22coreTemplate%22:%7B%22spec%22:%7B%22volumeClaimTemplates%22:%7B%22accessModes%22:%5B%22ReadWriteOnce%22%5D,%22resources%22:%7B%22requests%22:%7B%22storage%22:%225Gi%22%7D%7D,%22storageClassName%22:%22nfs-client%22%7D%7D%7D,%22dashboardServiceTemplate%22:%7B%22spec%22:%7B%22type%22:%22LoadBalancer%22%7D%7D,%22image%22:%22registry.cn-hongkong.aliyuncs.com/bcldops/emqx:5.8.3%22,%22listenersServiceTemplate%22:%7B%22spec%22:%7B%22type%22:%22LoadBalancer)”}}}}
name: emqx
namespace: default
spec:
coreTemplate:
metadata: {}
spec:
containerSecurityContext:
runAsGroup: 1000
runAsNonRoot: true
runAsUser: 1000
livenessProbe:
failureThreshold: 3
httpGet:
path: /status
port: dashboard
initialDelaySeconds: 60
periodSeconds: 30
podSecurityContext:
fsGroup: 1000
fsGroupChangePolicy: Always
runAsGroup: 1000
runAsUser: 1000
supplementalGroups:
- 1000
readinessProbe:
failureThreshold: 12
httpGet:
path: /status
port: dashboard
initialDelaySeconds: 10
periodSeconds: 5
replicas: 2
resources: {}
volumeClaimTemplates:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 5Gi
storageClassName: nfs-client
dashboardServiceTemplate:
metadata: {}
spec:
type: LoadBalancer
status:
loadBalancer: {}
image: ‘[registry.cn-hongkong.aliyuncs.com/bcldops/emqx:5.8.3](http://registry.cn-hongkong.aliyuncs.com/bcldops/emqx:5.8.3)’
imagePullPolicy: IfNotPresent
listenersServiceTemplate:
metadata: {}
spec:
type: LoadBalancer
status:
loadBalancer: {}
replicantTemplate:
metadata: {}
spec:
containerSecurityContext:
runAsGroup: 1000
runAsNonRoot: true
runAsUser: 1000
livenessProbe:
failureThreshold: 3
httpGet:
path: /status
port: dashboard
initialDelaySeconds: 60
periodSeconds: 30
podSecurityContext:
fsGroup: 1000
fsGroupChangePolicy: Always
runAsGroup: 1000
runAsUser: 1000
supplementalGroups:
- 1000
readinessProbe:
failureThreshold: 12
httpGet:
path: /status
port: dashboard
initialDelaySeconds: 10
periodSeconds: 5
replicas: 2
resources: {}

**Comment by Rory-Z** [comment]
Please use Markdown syntax to format your issue and fill in the content according to the issue template.

**Comment by wangchao732** [comment]
> Please use Markdown syntax to format your issue and fill in the content according to the issue template.
> 
> And it seems that the title has no relation to the content, please make sure the title is right.

Hi,
  First, how tto   configure externalTrafficPolicy,By the service configuration has been automatically restored.
  Second, An error occurred while configuring in CRDS. EMQX-exporter Keep restarting. The log is as above, and the modification prompt was successful, but the configuration did not take effect and change.
